# Generated by Django 5.1.4 on 2025-01-15 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0006_post_author_post_snippet_alter_post_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='snippet',
            field=models.CharField(max_length=500),
        ),
    ]
